# Generated by Django 3.2 on 2024-01-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_newquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewQuestion',
        ),
        migrations.CreateModel(
            name='NewQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.question',),
        ),
    ]
